### ISSUE TITLE
handle exception when received SIGINT while reading from the response.

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#393]
```
127.0.0.1:6379> blpop abc 10
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xintao.lai/Programs/iredis/iredis/entry.py", line 458, in main
    repl(client, session, enter_main_time)
  File "/Users/xintao.lai/Programs/iredis/iredis/entry.py", line 207, in repl
    for answer in answers:
  File "/Users/xintao.lai/Programs/iredis/iredis/client.py", line 405, in send_command
    redis_resp = self.execute(command_name, *args)
  File "/Users/xintao.lai/Programs/iredis/iredis/client.py", line 211, in execute
    return self.execute_by_connection(self.connection, *args, **kwargs)
  File "/Users/xintao.lai/Programs/iredis/iredis/client.py", line 236, in execute_by_connection
    response = connection.read_response()
  File "/usr/local/var/pyenv/versions/3.7.5/envs/iredis/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/var/pyenv/versions/3.7.5/envs/iredis/lib/python3.7/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/usr/local/var/pyenv/versions/3.7.5/envs/iredis/lib/python3.7/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/usr/local/var/pyenv/versions/3.7.5/envs/iredis/lib/python3.7/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/var/pyenv/versions/3.7.5/envs/iredis/lib/python3.7/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
KeyboardInterrupt
```

**Comment by laixintao** [comment]
not sure if this is necessary though.
since for `redis-cli`, there is no way to exit `BLPOP` without quit client.
If we do this in iredis, when we have to destroy the current connection and then create a new one.
