### ISSUE TITLE
cannot use on macos Big sur

### ISSUE THREAD

**Issue by SamSalvatore** [laixintao/iredis#404]
when i run  `iredis -h xxxx  -p xxxx` 
I got this error, but i dont know why

```
Traceback (most recent call last):
  File "/usr/local/bin/iredis", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/iredis/1.9.4_1/libexec/lib/python3.10/site-packages/iredis/entry.py", line 426, in main
    client = create_client(ctx.params)
  File "/usr/local/Cellar/iredis/1.9.4_1/libexec/lib/python3.10/site-packages/iredis/entry.py", line 402, in create_client
    return Client(
  File "/usr/local/Cellar/iredis/1.9.4_1/libexec/lib/python3.10/site-packages/iredis/client.py", line 97, in __init__
    self.auth_compat(config.version)
  File "/usr/local/Cellar/iredis/1.9.4_1/libexec/lib/python3.10/site-packages/iredis/client.py", line 159, in auth_compat
    with_username = StrictVersion(redis_version) >= StrictVersion("6.0.0")
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '5.0.9.23.1'
```

**Comment by laixintao** [comment]
it is nothing to do with Big Sur.

iredis failed the redis version check. `'5.0.9.23.1'` is not a valid redis version, where did you get this?

![image](https://user-images.githubusercontent.com/9675939/140448362-7a1bf28e-8130-4c0a-a97c-d7055e66c662.png)
