### ISSUE TITLE
No module named "six" issue after `brew install iredis`

### ISSUE THREAD

**Issue by zhangddjs** [laixintao/iredis#480]
``` bash
➜  ~ iredis
Traceback (most recent call last):
  File "/usr/local/bin/iredis", line 5, in <module>
    from iredis.entry import main
  File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/entry.py", line 19, in <module>
    from .client import Client
  File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/client.py", line 24, in <module>
    from . import markdown, renders
  File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/renders.py", line 14, in <module>
    from .config import config
  File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/config.py", line 5, in <module>
    from configobj import ConfigObj, ConfigObjError
  File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/configobj/__init__.py", line 22, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

also another issue that after I wget on a linux server, it outputs the following errors, can you help checkcheck, thanks:

``` bash
root@pt-dev:~#  ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
root@pt-dev:~# iredis
iredis: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by iredis)
iredis: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by iredis)
iredis: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by iredis)
iredis: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by iredis)
```

**Comment by zhangddjs** [comment]
also there seems to be some caveats from `brew install`
``` bash
![image](https://github.com/laixintao/iredis/assets/30108045/073cad17-4958-4322-a2c4-7be7b427bc95)
```

**Comment by laixintao** [comment]
> ```shell
> ➜  ~ iredis
> Traceback (most recent call last):
>   File "/usr/local/bin/iredis", line 5, in <module>
>     from iredis.entry import main
>   File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/entry.py", line 19, in <module>
>     from .client import Client
>   File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/client.py", line 24, in <module>
>     from . import markdown, renders
>   File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/renders.py", line 14, in <module>
>     from .config import config
>   File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/iredis/config.py", line 5, in <module>
>     from configobj import ConfigObj, ConfigObjError
>   File "/usr/local/Cellar/iredis/1.14.0/libexec/lib/python3.12/site-packages/configobj/__init__.py", line 22, in <module>
>     import six
> ModuleNotFoundError: No module named 'six'
> ```
> 
> also another issue that after I wget on a linux server, it outputs the following errors, can you help checkcheck, thanks:
> 
> ```shell
> root@pt-dev:~#  ldd --version
> ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> root@pt-dev:~# iredis
> iredis: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by iredis)
> iredis: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by iredis)
> iredis: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by iredis)
> iredis: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by iredis)
> ```

For brew issue, it seems that configobj havn't support python 3.12 yet: https://github.com/DiffSK/configobj (and also pendulum lib), so iredis havn't officially support 3.12, maybe can try an older version for now?

For the wget issue, from your output (very useful!), it's because your ubuntu only have glibc 2.31 but iredis need 2.32 onwards. I use ubuntu 22.04 to build this binary, maybe I can try to build it on an older version of ubuntu.

**Comment by laixintao** [comment]
> also there seems to be some caveats from `brew install`
> 
> ![image](https://user-images.githubusercontent.com/30108045/279598389-073cad17-4958-4322-a2c4-7be7b427bc95.png)`

For this one, the caveats was about php, and seems triggered by `brew cleanup php`, so it's not related to iredis as iredis was written in Python, iredis doesn't use php at all.

**Comment by zhangddjs** [comment]
cool, looking forward to the fixing for the old ubuntu version, I am going to install on our  dev env machine, so that my colleagues can use this iredis client :D
