### ISSUE TITLE
Install from pypi when click-8.0 released.

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#81]

**Comment by laixintao** [comment]
```
source = ctx.get_parameter_source("port")
```

We need this method to check whether an option is default or from user input.

**Comment by Junnplus** [comment]
iredis raise a error for click8
```
[I] ➜ iredis
Traceback (most recent call last):
  File "/Users/jun/.pyenv/versions/iredis/bin/iredis", line 10, in <module>
    sys.exit(main())
  File "/Users/jun/.pyenv/versions/3.8.0/envs/iredis/lib/python3.8/site-packages/iredis/entry.py", line 179, in main
    ctx = gather_args.main(standalone_mode=False)
  File "/Users/jun/.pyenv/versions/3.8.0/envs/iredis/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jun/.pyenv/versions/3.8.0/envs/iredis/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jun/.pyenv/versions/3.8.0/envs/iredis/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jun/.pyenv/versions/3.8.0/envs/iredis/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jun/.pyenv/versions/3.8.0/envs/iredis/lib/python3.8/site-packages/iredis/entry.py", line 159, in gather_args
    if ctx.get_parameter_source("raw") == click.ParameterSource.COMMANDLINE:
AttributeError: 'Context' object has no attribute 'get_parameter_source'
```

i think it should be compatible with flask
```
[I] ➜ pip freeze
Click==7.0
click8==8.0.1
Flask==1.1.1
iredis==0.7.0
```

**Comment by laixintao** [comment]
There is a package conflict with you virtualenv, please uninstall Click==7.0 and try again.

The reason is, that I used a function that only exist in Click==8.0, since it didn't release this version yet, I uploaded a fork(click8) to pypi. So where are two clicks exist in your enviroment.

**Comment by laixintao** [comment]
May be fixed by https://github.com/laixintao/iredis/pull/223

**Comment by laixintao** [comment]
fixed by https://github.com/laixintao/iredis/pull/223
